# Welcome!

In [3]:
import pandas as pd
import numpy as np

## Loading up the Video Games Sales Dataset

### The Main Focus is to grasp the main idea of the dataset to handle Data types And, Identifying Missing Values.

In [6]:
df = pd.read_csv(r"C:\Users\HP\Downloads\vgsales.csv\vgsales.csv")
df.head(7)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01

In [7]:
df.sample(15)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
7054,7056,Airblade,PS2,2001.0,Sports,Sony Computer Entertainment,0.11,0.09,0.00,0.03,0.23
15571,15574,WorldShift,PC,2009.0,Strategy,Playlogic Game Factory,0.02,0.00,0.00,0.00,0.02
3627,3629,Lunar: Silver Star Story Complete,PS,1998.0,Role-Playing,Kadokawa Shoten,0.27,0.18,0.06,0.04,0.55
15991,15994,Donkey Kong Jungle Beat,Wii,2008.0,Platform,Nintendo,0.00,0.01,0.00,0.00,0.01
12131,12133,Tropix,DS,2008.0,Puzzle,Capcom,0.06,0.00,0.00,0.00,0.07
10862,10864,Terranigma,SNES,1995.0,Role-Playing,Nintendo,0.00,0.00,0.09,0.00,0.09
2220,2222,Nickelodeon Fit,Wii,2010.0,Sports,Take-Two Interactive,0.78,0.09,0.00,0.06,0.93
5327,5329,Aggressive Inline,PS2,2002.0,Sports,Acclaim Entertainment,0.17,0.13,0.00,0.04,0.35
10203,10205,Shin Sangoku Musou 6 Special,PSP,2011.0,Action,Tecmo Koei,0.00,0.00,0.11,0.00,0.11
3570,3572,NCAA March Madness 07,PS2,2007.0,Sports,Electronic Arts,0.28,0.22,0.00,0.07,0.56
6505,6507,The Elder Scrolls IV: Oblivion,PC,2006.0,Role-Playing,Take-Two Interactive,0.01,0.20,0.00,0.05,0.26
8791,8793,Frogger's Adventures: The Rescue,GC,2003.0,Platform,Konami Digital Entertainment,0.12,0.03,0.00,0.00,0.15
9359,9361,Puzzle Kingdoms,DS,2009.0,Puzzle,Zoo Digital Publishing,0.12,0.00,0.00,0.01,0.13
163,164,Mario Kart: Super Circuit,GBA,2001.0,Racing,Nintendo,2.62,1.64,0.99,0.23,5.47
11470,11472,Prey the Stars,DS,2008.0,Action,Tecmo Koei,0.07,0.00,0.00,0.01,0.08

In [8]:
df.shape

(16598, 11)

In [9]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [11]:
df['Year'] = df['Year'].astype('Int64')

In [12]:
df['Year']=df['Year'].fillna(np.nan)

#### Handled missing Year values appropriately using NaN rather than introducing misleading numerical estimates.

#### Same for Publisher column.

In [15]:
df['Publisher'].isna().sum()

58

In [16]:
df['Publisher'] = df['Publisher'].fillna(np.nan)

#### Last check-up before wraping up.

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  Int64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: Int64(1), float64(5), int64(1), object(4)
memory usage: 1.4+ MB